name: Build and Deploy Code   #the name can be anything you want

on: [push, pull_request]      #this will trigger the workflow on push and pull request events

jobs:                         #this is where you define the jobs that will run in the workflow
  build:                       #this is the name of the job, you can name it anything you want
    environment: testings
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
        #this is how you can access the secrets you have set up in your repository, you can use it in your code as an environment variable

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest    #this specifies the operating system that the job will run on
    steps:
      - name: pulling git repo  #this is the name of the step, you can name it anything you want
        uses: actions/checkout@v4 #this is the action that will pull the code from the git repository, you can specify the version of the action you want to use
      - name: Install python  #this is another step, you can add as many steps as you want
        uses: actions/setup-python@v6  #this is the action that will set up python on the runner, you can specify the version of python you
        with:
          python-version: "3.12" #this specifies the version of python you want to use, you can change it to any version you want
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt  #this will install the dependencies specified in the requirements.txt file, you can change it to any command you want to run
      - name: Run tests with pytest #this will install pytest and run the tests, you can change it to any command you want to run
        run: |
          pip install pytest
          pytest 

## this part is optional and it will build and push the docker image to dockerhub, you can skip this part if you don't want to do it
##im gonna comment it out for now...
#      - name: Login to Docker Hub
#        uses: docker/login-action@v4
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v4
#
#      - name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v7
#        with:
#          context: ./
#          file: ./Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi:latest
#          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/fastapi:buildcache
#          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/fastapi:buildcache,mode=max
#      - name: Image digest
#        run: echo ${{ steps.docker_build.outputs.digest }} 

  deploy:
    enviroment: production
    runs-on: ubuntu-latest
    needs: build              #this means that the deploy job will only run if the build job is successful

    steps:
      - name: deploying stuffs
        run: echo "going to deploy some stuffshere..."
      # login to our ubuntu server
      # cd /app/src
      # git pull
      # systemctl restart api.service

      - name: Deploy to My Ubuntu Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.PROD_HOST}}
          username: ${{secrets.PROD_USERNAME}}
          password: ${{secrets.PROD_PASSWORD}}
          script: |
            cd app/src
            git pull
            sudo systemctl restart fastapi.service
